apiVersion: apps/v1
kind: Deployment
metadata:
  name: tupian-demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge:
      maxUnavailable: 0
  minReadySeconds: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tupian-demo
  template:
    metadata:
      labels:
        app: tupian-demo
    spec:
      containers:
        - name: tupian-demo
          image: registry.cn-hangzhou.aliyuncs.com/wuchenyang/tupian-demo:test-c9acbb
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1024Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: tupian-demo
spec:
  selector:
    app: tupian-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort