const style = require('./app.css');
const style2 = require('./app.less');
const styl3 = require('./app.styl');
const t = require('./app.txt');
const logo = require('./timg.jpeg');
console.log(t, 't');
document.write('<p>123123</p>');
document.write('<span>abcd</span>');
document.write('<div>123hnvg</div>');
document.write('<div>' + t.default + '</div>');
document.write('<img src=' + logo.default + ' />');
